name: Run Unit Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  DevOpsPRUnitTests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin     
      - name: Build Private Dependencies And Test
        run: |
          sudo apt install -y jq
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GitHubToken }}" >> ~/.npmrc
          npm install
          npm run build
          npm test -- -u